---
title: "1.Gene model assessment"
author: "CTLai"
date: "March 31, 2018"
output: html_document
---

###Gene model assessment
In the previous video, we saw that a gene can have different transcripts, with potential different starting points and ending points, different exons, similar exons but with different lengths, etc.

In this short assessment, we will look up specific genes in the UCSC Genome Browser, to investigate the gene model, that is, the different exons of the different transcripts.

1. Go to the UCSC Genome Browser and set the genome assembly to Feb 2009 (GRCh37/hg19).

2. Search for the gene, "RIT1".

3. Click the top link on the next page.

4. Zoom out 1.5x.

5. Read the section "Gene prediction tracks" in the section, "Interpreting and fine-tuning the Genome Browser display".

####Gene model Q1
According to the UCSC Genes track (it will be on top if you have the default arrangement), how many transcripts does RIT1 have? Note that the RefSeq Genes track below is a separate annotation of the same gene.

#####ANS: 3

####Gene model Q2
According to UCSC Genes track, how many exons does the top transcript of RIT1 (uc031pqc.1) have?

#####ANS: 6

####Gene model Q2
Look up a nearby gene, CCT3. How many transcripts does this gene have, according to the UCSC Genes track?

#####ANS: 5
